homeassistant:
  # auth_providers:
  #   - type: homeassistant
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 391
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
alarm_control_panel: !include alarm.yaml
alert: !include alert.yaml
amcrest: !include amcrest.yaml
automation: !include_dir_merge_list automations
# binary_sensor: !include binary_sensor.yaml
calendar: !include calendar.yaml
camera: !include camera.yaml
climate: !include climate.yaml
config:
  # base_url: example.duckdns.org:8123 # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
conversation:
cover: !include covers.yaml
custom_updater:
device_tracker: !include device_tracker.yaml
discovery:
# google: !include google.yaml
group: !include groups.yaml
history:
http: !include http.yaml
shell_command: !include shell_command.yaml
frontend: !include frontend.yaml
influxdb: !include influxdb.yaml
input_boolean: !include input_boolean.yaml
# input_number: !include input_number.yaml
input_text: !include input_text.yaml
# light: !include lights.yaml
logbook:
logger:
  default: info
map:
media_player: !include media_player.yaml
notify: !include notify.yaml
openuv: !include openuv.yaml
panel_iframe: !include iframe.yaml
# personalcapital: !include personal_captial.yaml
python_script:
rest_command: !include rest_command.yaml
# script: !include_dir_merge_list scripts
script: !include scripts.yaml
sensor: !include sensors.yaml
shopping_list:
lists:
sun:
telegram_bot: !include telegram_bot.yaml
tts: !include tts.yaml
updater: !include updater.yaml
weather: !include weather.yaml
# zha: !include zha.yaml
zone: !include zones.yaml
zwave: !include zwave.yaml



















